language: node_js
node_js:
- '8'
- '10'
cache: yarn
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
- npm run ci
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  skip_cleanup: true
  email: rplan-ci@actano.de
  on:
    tags: true
    repo: actano/borders-couchbase-client
    node: '8'
  api_key:
    secure: OFKIoGdADBJ608SwsQFnL/v2c2HemU/B/XPBmdLA7Q7JRP4X/3OhnxGrZCam2TO/xGkurcBLG4lBAwAwxe+/a2CJSNVOceq8tvHl7z8FvDF4eUQmKTVpjVuqBg33oYkQcD+YsNLOrzhVYG7as2OLhu9c5/Ob12N4rf2qawmlG6gsxskdpgJs3Qjg+c4ZjB7ezoPDh3tz3YHwKwsImpsQkZO5w0yInbHzBfu3aCrr58T0d6cE8o2ET0KVn8toBlc569acYzeu5RKmXndNCzj/PDfzF265rvTbk5W7GJmGzzYAmyw1ADWIRl4z1C94MVfoCyUo7s8ZHT1Uz0p6JT5jFir26IOMsL5KClyV9jCXR0oyrLD6tJS0e3cBy911KaVx75IReHcn2Sm/+rnIQEB9ZqAcno8y0/7qBab54U8bbPE+ilKcJFrdShwAuLPkjVVZoKtAT9EMSlrn9gxteZHaORuRzXYvAe9vfJqFWxftSdKZL/TeC1/DWzWCgPrta/CMjwFPB7Ib91cQSLtrsGRNaCCLfhHgCgrQsuDk4iYMWfP9pUll+WFTHH7josTWv955vLrD1hZQ0So4uaTrC1bnWGUBjuoGy1BzbFcy0JcqBVNhHjmGW7MUC4H/xhiCHB3GtyNrVMWFSyOIxT153C4MhYZWOa0yhK7KNVQQ0JQ0Yhg=
env:
  global:
    secure: OD3uizDyop+7IvVzRi3Zy17x6kLvKymlxY8nNEGvhE0WzO4Apc1cJ8qNt5lcWYxF9JBxzB4QVQ/BSy4CUxjbLJ/cRm5JeIWtoCcZa+fzQyx/lKZoIUvo5aYa1JwS6exp+hQGlVRCmzkFUQRvqch3FsTTlc0uLzkrox/XN9MB9NaVBFNfz8HKhSCYVXf+woji3cFwc6hg0sZFwYZmaOvyChOxKnbZrh8U1n4Uz5QJ06BQdlJppxLtpkknzQJqsPxR5ip5TsnqXbv1/IzAWQ+9JfXhyztEQbGsYqYPcL6HTL6tGaqiAR4ANEFSToOKdXjR1WlYk5UGIKdrJf7Hn/OFfcNVgmbK6Ynk5+taNIEPzIJaoFEh8PyOiopw0cHBFeT/4bEivdumUQTctpQvIsG4yZmkcT5WfmIUXwSiHwthQKil4JMzQaSkABwWsm4cVCMi/Uu9o23StoLBl60AKmUdtKB+0T9KMdTYTUIoOOlx2vtsCSZO7KTLb5K61vsXcmtlKsp9QDdZdd24wBLZegMiFVpOkLTfr0yqViEdSBr1c6Pl85dmEI4PREBfi/KlyxrMeMkegZxuHvVv1NzU1z3rb7bvZ0ieTSJegOuFShae4Xv8N0ln+NApHqggLgZnvBIrQIezjZrTfLg4TnsXzg+rdKGRtokaBJ+GkO1/23Th/tM=
