language: node_js
node_js:
- '8'
cache: yarn
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
- npm run ci
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  skip_cleanup: true
  email: hello@rplan.com
  on:
    tags: true
    repo: actano/borders-couchbase-client
    node: '8'
  api_key:
    secure: Covc8lOI+6qWanAGiC5mv/hNMjJiwlFu5xK4HbgU76/OgOQfGcmU/KmNrSukpYrByC3/CojhEGvNioVfPtH6zSwB7hj/Io+74m3G4xt1a/ObfVBI5+cOtyP0Cn+U/nyXDnO4nWJhkwcmqh3OCZwHApZOq7+wUj3RGYChO20eFr/1qwgqZV0ehd40qjh56GhbSFTfw3xC3IXQ3ZoWQZ5qWRWTC1QXd8HRgK1b2fcMbwQEU2VeHgKrNcvHLfPhRiumnUrXxKW1cU9TZV69FFvhABCcPtb1Pxc/BIuPs1BbEDnm6Ww6iTnYqOgoihx9M7QW6j0jHn3vbJ8Dn5u6KwLSbme/Debz99A1FrMSsthcEmoPrh4G8pDHyKXmLJi0Jgk9QtlGKiXMpSbhavM+c8LEGyZtt+QEF+dcdNKpTFImbcpdCbCOShArpSeEVEqzKgX1bISSGo9ereFZL/ibyPO1Ww7kTBInJakyivP29pH/bXuZ0vXo4dYyKMn6oJK7i2ueH2iFbz2RwXMAENzNy/kL/KC91N7/qXu6PS5rEIu4ahjEOd2pZ+KHw3Kar/at7GvpmyzmTfuRZRG4QVY6fGMr/K6GCbXtGwqYd+xefxWiZn4pCYwfSa45uopMXDpU0HUbTgQ7E2EzlZ0ykqvpyy5iIbmyMqxnM6e0866tBRL5jJE=
env:
  global:
    secure: OD3uizDyop+7IvVzRi3Zy17x6kLvKymlxY8nNEGvhE0WzO4Apc1cJ8qNt5lcWYxF9JBxzB4QVQ/BSy4CUxjbLJ/cRm5JeIWtoCcZa+fzQyx/lKZoIUvo5aYa1JwS6exp+hQGlVRCmzkFUQRvqch3FsTTlc0uLzkrox/XN9MB9NaVBFNfz8HKhSCYVXf+woji3cFwc6hg0sZFwYZmaOvyChOxKnbZrh8U1n4Uz5QJ06BQdlJppxLtpkknzQJqsPxR5ip5TsnqXbv1/IzAWQ+9JfXhyztEQbGsYqYPcL6HTL6tGaqiAR4ANEFSToOKdXjR1WlYk5UGIKdrJf7Hn/OFfcNVgmbK6Ynk5+taNIEPzIJaoFEh8PyOiopw0cHBFeT/4bEivdumUQTctpQvIsG4yZmkcT5WfmIUXwSiHwthQKil4JMzQaSkABwWsm4cVCMi/Uu9o23StoLBl60AKmUdtKB+0T9KMdTYTUIoOOlx2vtsCSZO7KTLb5K61vsXcmtlKsp9QDdZdd24wBLZegMiFVpOkLTfr0yqViEdSBr1c6Pl85dmEI4PREBfi/KlyxrMeMkegZxuHvVv1NzU1z3rb7bvZ0ieTSJegOuFShae4Xv8N0ln+NApHqggLgZnvBIrQIezjZrTfLg4TnsXzg+rdKGRtokaBJ+GkO1/23Th/tM=
